### ISSUE TITLE
イベントまとめをWordPressへ

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/chn#19]
@kenchif さんと話あってアカウントは作ったし、準備もした、下書きもかいた。

今後は、フローを決めて毎度担当者にお願いする。

**Comment by PharaohKJ** [comment]
http://codeforkanazawa.org/chn201705/

公開した。Facebookでも案内した。

**Comment by PharaohKJ** [comment]
@kenchif 

WordPressに手を入れたいのですが、ソースコード入手方法、更新方法など教えてください。
あとアップデートはいつ誰がやっているのですか？手順、担当などあったら教えてください。

**Comment by PharaohKJ** [comment]
@kenchif 

CfKのページにFAQへのリンクを作ってはどうか？と要望が結構きてるのですが、いかがでしょうか。

**Comment by PharaohKJ** [comment]
@kenchif @kiyohara さんと相談して進めます。

**Comment by PharaohKJ** [comment]
@kiyohara さん、今度どういう運用になったか教えてください。
やりたいことを具体的にいうと、CSS追加したい。

**Comment by kiyohara** [comment]
@PharaohKJ 運用ルールの策定には至ってないですが、編集するために必要な情報はシェアしてもらった状態です。変更の是非については理事（たとえば清原）判断で対応できます。コンテンツ以外の部分での変更がある場合は、松尾さんにも連絡しつつ変更しています。

css の追加ということなので、顔つきあわせて対応しましょうか。
chn に参加できそうな見通しなので、そのタイミングとか。どうでしょう。

**Comment by PharaohKJ** [comment]
ok わかりました。

**Comment by PharaohKJ** [comment]
CSS追加 & 記事テンプレ設定してもらえた。たぶんOK。
