### ISSUE TITLE
FAQとイベントまとめについて資料作成

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/chn#21]
2017-06-08のCHNまでには作成し、プレゼンする。

**Comment by PharaohKJ** [comment]
https://www.icloud.com/keynote/0Wia6XgRnpz9AL-hmgH9UJ6sA

**Comment by kiyohara** [comment]
いいっすね、いいっすね。

この資料自体は今回一発ものだと思うのですが、こういった資料がシェアされて、他の人も使えるようになっているとよりグッドだなあと妄想しました。
その場合、体裁整えたり（ファランクスウェアとか加藤さんの名前とか削る）シェアのしかたも考えないといけないのだけど…
某勉強会では、 Dropbox で .key をシェアしてるし、イベント毎に対応できる人がコピーして使い回しているのだけど、ああいう形にまで昇華できるとよいっすね。

※運営協力者の技量を揃えるのは難しいよねという気持ちもありつつ

**Comment by PharaohKJ** [comment]
https://github.com/codeforkanazawa-org/chn

いちおう本リポジトリに資料置いていきましょうってことにはなってるんだけど、形式とかについてはまだまだ。

macじゃない人も考えないといけないとかいろいろ考えちゃうとキリがないんでいったんこれでいこうと考えてます。
