### ISSUE TITLE
オープニングトーク資料の共有

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/chn#3]
@kenchif さん、オープニングトーク（= シビックテック・ハックの説明）の資料を私も使えるように共有してください。

GitHubでもDropboxでもEvernoteでも共有方法はおまかせします。

**Comment by kenchif** [comment]
@PharaohKJ リポジトリにアップしました。

**Comment by PharaohKJ** [comment]
ありがとうございます。
