### ISSUE TITLE
2017-05 - SNSで集客する

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/chn#4]
- twitter
  - [ ] 2週前
  - [ ] 1週前
  - [ ] 前日
- facebook
  - [ ] 2週前
  - [ ] 1週前
  - [ ] 前日

**Comment by kenchif** [comment]
やりはじめています。fbについては招待状も出しました。

**Comment by PharaohKJ** [comment]
シェアしておきました。

**Comment by PharaohKJ** [comment]
シェアしました。
