### ISSUE TITLE
codeforkanazawa.org の SSL 化

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/chn#43]
codeforkanazawa.org の SSL 化

https://www.sakura.ad.jp/press/2017/1010_lets-encrypt/

**Comment by PharaohKJ** [comment]
SEO的な意味でもお願いします。

**Comment by PharaohKJ** [comment]
@kenchif 対応よろしくおねがいします。

**Comment by PharaohKJ** [comment]
@kenchif 対応よろしくおねがいします 2nd

**Comment by kenchif** [comment]
@PharaohKJ 遅くなってすみません。設定申し込みは終わりました。
"ただいま無料SSL証明書の発行手続き中です。 発行完了後にメールでお知らせしますので今しばらくお待ちください。発行には数十分〜数時間かかる場合があります。"とのことです。

**Comment by kenchif** [comment]
@PharaohKJ 設定完了しました。
https://codeforkanazawa.org/
