### ISSUE TITLE
2017-05 - 内容・場所・日時を決める

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/chn#5]
- [x] Facebook イベントを作成
  - 詳細はconnpass参照とする
- [x] connpassイベントを作成
- [x] 企画する(基本 meetup)
- [x] 場所を決める
  - 金沢中心でありつつも、できれば石川県単位で。
- [x] 会場費を支払い場所を抑える
  - 領収書は「一般社団法人コード・フォー・カナザワ」で必ずもらうこと。
- [x] 懇親会もあれば手配する
  - 領収書は「一般社団法人コード・フォー・カナザワ」で必ずもらうこと。

**Comment by PharaohKJ** [comment]
企画は meetup で。
導入プレゼン > LT > 議論。

**Comment by PharaohKJ** [comment]
@kenchif さん、ATNDとかFacebookイベントって誰が作ることできるんです？権限的に私でも可能になるのならば、ちょっとそれどうやって手分けするか教えて欲しいです。

**Comment by PharaohKJ** [comment]
日時:  5/11(木) 19:00 - 
場所:  ITビジネスプラザ武蔵サロンスペース でいいですか？

**Comment by kenchif** [comment]
@PharaohKJ 会場ですが、ITBP武蔵サロンスペース"CRIT"を予約しました。無料利用できるため、今回は会計処理はありません。

**Comment by kenchif** [comment]
@PharaohKJ イベントページですが、Connpassとfacebookの二つになります。facebookはCivicHackNightのfacebookページの管理者がイベントを立てることができるので、そのページの管理者として登録させて頂きました。
Connpassについては、メッセージにてアカウント情報を送ります。

**Comment by PharaohKJ** [comment]
https://cfk.connpass.com/event/56333/
https://www.facebook.com/events/1502361256448761/

作成済み。権限は @kenchif さんにいただきました。
基本、これの「複製」で延々といけるはず。

Vol.20のレポートはあとで追加していただけるのでその後追加予定。
