### ISSUE TITLE
2017-05 - 当日の担当を手配する

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/chn#6]
- [x] 司会の割当
- [x] シビックテック説明の割当
  - スライドを用いて説明を行う
- [x] 入門者卓ガイドの割当
- [x] 上級者卓ファシリテータの割当
- [x] 写真撮影

**Comment by PharaohKJ** [comment]
@kenchif さん、司会とシビックテック説明お願いしていいですか？

**Comment by kenchif** [comment]
@pharaohKJ さん、了解です。

**Comment by PharaohKJ** [comment]
今回は入門者卓ガイド、上級卓ガイドについて、私(@PharaohKJ) がプレゼンするにとどめます。

**Comment by kenchif** [comment]
写真撮影は、@kenchif が記録程度で撮りますね。あとは参加者の人たちが撮ったものをもらいます。

**Comment by PharaohKJ** [comment]
ありがとうございます。そうですね、参加者の方々にハッシュタグ `#cfkchn` で写真をSNS(Facebook/twitter/instagram?)で投稿してもらうよう連絡しましょう。

オープニングトークにこのむね入れていただいてよいですか？ > @kenchif

**Comment by kenchif** [comment]
@PharaohKJ 了解です。ハッシュタグ、いいですね。以前から使うべきでした。他のイベントでは使っていたのに。
